In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
from sklearn.impute import KNNImputer
dataset=pd.read_csv('HousingData.csv')
imputer = KNNImputer(n_neighbors=5)
dataset.iloc[:, :] = imputer.fit_transform(dataset)


In [33]:
X=dataset.iloc[:,0:-1].values
y=dataset.iloc[:,-1].values
print(X)
print(y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [34]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
X[:,2]=labelencoder.fit_transform(X[:,2])
print(X)

[[6.3200e-03 1.8000e+01 1.9000e+01 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 6.3000e+01 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 6.3000e+01 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 7.7000e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 7.7000e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 7.7000e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=50)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[7.52601e+00 0.00000e+00 8.30000e+01 ... 2.02000e+01 3.04210e+02
  1.93100e+01]
 [1.84982e+01 0.00000e+00 8.30000e+01 ... 2.02000e+01 3.96900e+02
  3.79700e+01]
 [3.68940e-01 2.20000e+01 5.10000e+01 ... 1.91000e+01 3.96900e+02
  3.54000e+00]
 ...
 [8.71675e+00 0.00000e+00 8.30000e+01 ... 2.02000e+01 3.91980e+02
  1.71200e+01]
 [5.82401e+00 0.00000e+00 8.30000e+01 ... 2.02000e+01 3.96900e+02
  1.07400e+01]
 [7.02200e-02 0.00000e+00 3.80000e+01 ... 1.66000e+01 3.93230e+02
  1.01100e+01]]
[[4.55587e+00 0.00000e+00 8.30000e+01 ... 2.02000e+01 3.54700e+02
  7.12000e+00]
 [2.69380e-01 0.00000e+00 7.20000e+01 ... 1.84000e+01 3.93390e+02
  7.90000e+00]
 [3.69311e+00 0.00000e+00 8.30000e+01 ... 2.02000e+01 3.91430e+02
  1.46500e+01]
 ...
 [2.68380e-01 0.00000e+00 7.00000e+01 ... 1.92000e+01 3.96900e+02
  1.41000e+01]
 [3.58400e-02 8.00000e+01 2.90000e+01 ... 1.61000e+01 3.96900e+02
  4.67000e+00]
 [7.15100e-02 0.00000e+00 4.10000e+01 ... 1.85000e+01 3.95150e+02
  9.84800e+00]]
[13.  13.8 42.8 

In [46]:
# trying gradient boosting regression
from sklearn.ensemble import GradientBoostingRegressor
regressor=GradientBoostingRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9281636183201456